repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff (lint)
        entry: uv run ruff check --fix
        language: system
        types: [python]
        pass_filenames: true

      - id: unittests
        name: Unit tests
        entry: uv run task unit
        language: system
        pass_filenames: false

      - id: mypy
        name: Mypy (type checks)
        entry: uv run mypy
        language: system
        pass_filenames: false